"""додав колонку is_active для IoT моделі

Revision ID: 5bc9026c7c3c
Revises: 6147866fcfb2
Create Date: 2024-07-23 03:38:49.905245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc9026c7c3c'
down_revision: Union[str, None] = '6147866fcfb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iot_devices', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iot_devices', 'is_active')
    # ### end Alembic commands ###
