"""Додано каскадне видалення до таблиці Акваріуму

Revision ID: fabe7f7d3432
Revises: 92c2d9ac04f2
Create Date: 2024-08-17 00:32:54.802857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fabe7f7d3432'
down_revision: Union[str, None] = '92c2d9ac04f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
